# Generated by Django 3.2.25 on 2024-11-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixifyuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
