# Generated by Django 3.2.25 on 2024-11-09 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_fixifyuser_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='fixifyuser',
            managers=[
            ],
        ),
    ]
